spring:
    application:
        name: error-server
    config:
        import: optional:configserver:http://localhost:8888
    datasource:
        url: jdbc:mysql://localhost:3306/courierdb?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
        password: root-workbench
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: error-logs-group
            properties:
                spring:
                    json:
                        value:
                            default:
                                type: com.courier.errorserver.model.dto.ErrorLogDto
            
            


server:
    port: 8082

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://localhost:8761/eureka/
