server:
    port: 8080

spring:
    application:
        name: spring-cloud-gateway
    cloud:
        gateway.discovery.locator.enabled: true
        config.enabled: false

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

