server:
    port: 8080

spring:
    application:
        name: spring-cloud-gateway
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    cloud:
        gateway:
            discovery.locator.enabled: true
            globalcors:
                add-to-simple-url-handler-mapping: true
                cors-configurations:
                    '[/**]':
                        allowed-origins: "http://localhost:5173"
                        allowed-methods: "*"
                        allowed-headers: "*"


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

