server:
    port: 8080

spring:
    application:
        name: spring-cloud-gateway
    cloud:
        gateway:
            discovery.locator.enabled: true
            globalcors:
                add-to-simple-url-handler-mapping: true
                cors-configurations:
                    '[/**]':
                        allowed-origins: "http://localhost:5173"
                        allowed-methods: "*"
                        allowed-headers: "*"
                        allow-credentials: true


eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    