server:
    port: 8080

spring:
    application:
        name: spring-cloud-gateway
    cloud:
        gateway:
            discovery.locator.enabled: true
            globalcors:
                add-to-simple-url-handler-mapping: true
                cors-configurations:
                    '[/**]':
                        allowed-origins: "http://localhost:5173"
                        allowed-methods: "*"
                        allowed-headers: "*"


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

